name: flutter_wordcloud
description: "Flutter's minimal word cloud library requires only a weight dictionary."

version: 1.0.2

homepage: https://github.com/PythonnotJava/flutter_wordcloud
repository: https://github.com/PythonnotJava/flutter_wordcloud

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  path_provider: ^2.1.5


flutter:

  uses-material-design: true

 